# Generated by Django 4.2 on 2024-07-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='SASASA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='desc_categoria_prod_principal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='desc_categoria_producto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='desc_ga_categoria_producto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='desc_ga_cod_producto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='desc_ga_marca_producto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='desc_ga_nombre_producto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='desc_ga_nombre_producto_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='desc_ga_sku_producto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='desc_ga_sku_producto_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='fc_agregado_carrito_cant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='fc_detalle_producto_cant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='fc_ingreso_producto_monto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='fc_producto_cant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='fc_retirado_carrito_cant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='fc_visualizaciones_pag_cant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='flag_pipol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceanalytics',
            name='id_ga_producto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
